services:
  backend:
    image: chatbot-backend:latest
    build:
      context: ../backend
      dockerfile: Dockerfile
    container_name: chatbot-backend
    ports:
      - "5000:5000"
    env_file:
      - ../backend/.env
      - ../backend/.env.production
    networks:
      - app-network

  frontend:
    image: chatbot-frontend:latest
    build:
      context: ../frontend
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_API_URL: https://chatbot-load-balancer-1863046690.eu-west-3.elb.amazonaws.com
    container_name: chatbot-frontend
    ports:
      - "3000:3000"
    env_file:
      - ../frontend/.env.production
    environment:
      - NODE_ENV=production
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
