name: ChatBot App CI/CD Pipeline
on:
  push:
  pull_request:
jobs:
  test:
    runs-on: ubuntu-latest
    name: Test the Application
    env:
      GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
      AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.13'
        cache: 'pip' # caching pip dependencies

    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: |
        pytest --maxfail=1 --disable-warnings -q
      # Ensure workflow stops on test failure
      continue-on-error: false

  build-deploy:
    runs-on: ubuntu-latest
    needs: test
    name: Build & Deploy To ECS
    if: success()
    # if: github.ref == 'refs/heads/main' && success()
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: 'eu-west-3'
      ECR_REPOSITORY: 'fine-tuned-liu-model'
      ECR_REGISTRY: '418295688401.dkr.ecr.eu-west-3.amazonaws.com'
      ECS_CLUSTER: 'your-ecs-cluster'  # Update with your cluster name
      ECS_SERVICE: 'your-ecs-service'  # Update with your service name

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Login to Amazon ECR
      id: login-ecr
      run: aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $ECR_REGISTRY

    - name: Build, tag, and push image to Amazon ECR
      id: build-image
      run: |
        # Build the Docker image
        docker build -t $ECR_REPOSITORY -f docker/Dockerfile .
        
        # Tag the image
        docker tag $ECR_REPOSITORY:latest $ECR_REGISTRY/$ECR_REPOSITORY:latest
        
        # Push the image to ECR
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:latest
        
        echo "::set-output name=image::$ECR_REGISTRY/$ECR_REPOSITORY:latest"

    # - name: Deploy to ECS service
    #   run: |
    #     aws ecs update-service --cluster $ECS_CLUSTER --service $ECS_SERVICE --force-new-deployment