name: ChatBot App CI/CD Pipeline
on:
  push:
    branches:
      - chatbot-app-deploy
    paths:
      - 'backend/**'
      - 'frontend/**'
  workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-latest
    name: Test the Application
    environment: production
    env:
      GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
      AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'
        cache: 'pip'
        cache-dependency-path: backend/requirements.txt

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: frontend/package-lock.json

    - name: Install frontend dependencies
      working-directory: ./frontend
      run: npm ci

    - name: Install dependencies
      working-directory: ./backend
      run: |
        pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: |
        export PYTHONPATH=$GITHUB_WORKSPACE/backend
        pytest --maxfail=1 --disable-warnings -q
      # Ensure workflow stops on test failure
      continue-on-error: false

  build-app:
    runs-on: ubuntu-latest
    needs: test
    environment: production
    name: Build and Deploy Chatbot App
    # if: github.ref == 'refs/heads/master' && success()
    if: success()
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: 'eu-west-3'
      ECR_REGISTRY: '418295688401.dkr.ecr.eu-west-3.amazonaws.com'
      ECS_TASK_DEFINITION: 'AI-Chatbot-Task-Defination'

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@0e613a0980cbf65ed5b322eb7a1e075d28913a83
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@62f4f872db3836360b72999f4b87f1ff13310f3a

    - name: Determine Changed Directory
      id: changes
      run: |
        CHANGED_FILES=$(git diff --name-only HEAD^ HEAD)

        BACKEND_CHANGED=$(echo "$CHANGED_FILES" | grep '^backend/' || true)
        FRONTEND_CHANGED=$(echo "$CHANGED_FILES" | grep '^frontend/' || true)

        # !!! For debugging purposes only !!!!
        echo "Changed files:"
        echo "$CHANGED_FILES"
        # !!! For debugging purposes only !!!!

        echo "backend_changed=$BACKEND_CHANGED" >> $GITHUB_OUTPUT
        echo "frontend_changed=$FRONTEND_CHANGED" >> $GITHUB_OUTPUT

    - name: Docker Build & Push
      run: |
        if [ -n "${{ steps.changes.outputs.backend_changed }}" ]; then
          echo "ðŸ”¨ Building and Pushing Backend"
          docker compose -f docker/docker-compose.yml build backend
          docker tag chatbot-backend:latest $ECR_REGISTRY/chatbot-backend:${{ github.sha }}
          docker tag chatbot-backend:latest $ECR_REGISTRY/chatbot-backend:latest
          docker push $ECR_REGISTRY/chatbot-backend:${{ github.sha }}
          docker push $ECR_REGISTRY/chatbot-backend:latest
        elif [ -n "${{ steps.changes.outputs.frontend_changed }}" ]; then
          echo "ðŸ”¨ Building and Pushing Frontend"
          docker compose -f docker/docker-compose.yml build frontend
          docker tag chatbot-frontend:latest $ECR_REGISTRY/chatbot-frontend:${{ github.sha }}
          docker tag chatbot-frontend:latest $ECR_REGISTRY/chatbot-frontend:latest
          docker push $ECR_REGISTRY/chatbot-frontend:${{ github.sha }}
        docker push $ECR_REGISTRY/chatbot-frontend:latest
        elif [ -n "" ]; then
          echo "No changes detected in backend or frontend directories. Skipping Docker build and push."
        else
          return 1
        fi

    - name: Download Task Definition
      run: |
        aws ecs describe-task-definition --task-definition ${{ env.ECS_TASK_DEFINITION }} --query taskDefinition > task-definition.json
      
    - name: Clean and Prepare Task Definition
      run: |
        jq 'del(.taskDefinitionArn, .revision, .status, .registeredAt, .registeredBy, .compatibilities, .requiresAttributes, .cpu, .memory)' task-definition.json > task-definition.cleaned.json
    
    - name: Update Images for Both Containers
      run: |
        jq --arg backend_image "$ECR_REGISTRY/chatbot-backend:${{ github.sha }}" \
           --arg frontend_image "$ECR_REGISTRY/chatbot-frontend:${{ github.sha }}" \
        '(.containerDefinitions[] | select(.name == "chatbot-backend") .image) = $backend_image |
         (.containerDefinitions[] | select(.name == "chatbot-frontend") .image) = $frontend_image' \
        task-definition.cleaned.json > task-definition.updated.json

    - name: Upload Task Definition Artifact
      uses: actions/upload-artifact@v4
      with:
        name: task-definition
        path: task-definition.json
        retention-days: 1

  deploy-app:
    runs-on: ubuntu-latest
    needs: build-app
    name: Deploy Application
    environment: production
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: 'eu-west-3'
      ECS_CLUSTER: 'Fine-Tuned-LLM-Model'
      ECS_SERVICE: 'Fine-Tuned-LLM-Model-Service'
    steps:

    - name: Download Task Definition Artifact
      uses: actions/download-artifact@v4
      with:
        name: task-definition

    - name: Register New Task Definition
      id: register-task
      run: |
        TASK_DEF_ARN=$(aws ecs register-task-definition \
          --cli-input-json file://task-definition.updated.json \
          | jq -r '.taskDefinition.taskDefinitionArn')
        echo "TASK_DEF_ARN=$TASK_DEF_ARN" >> $GITHUB_OUTPUT

    - name: Deploy to Amazon ECS
      uses: aws-actions/amazon-ecs-deploy-task-definition@v2
      with:
        task-definition: ${{ steps.register-task.outputs.task_def_arn }}
        service: ${{ env.ECS_SERVICE }}
        cluster: ${{ env.ECS_CLUSTER }}
        wait-for-service-stability: true

  cleanup-phase:
    runs-on: ubuntu-latest
    needs: [build-app]
    name: Cleanup Phase
    if: success()
    steps:
    - name: Remove Task Definition Artifact
      run: |
        echo "Cleaning up task definition artifact artifact"


    
